# Generated by Django 5.0.1 on 2024-02-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_post_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='account',
            new_name='author',
        ),
    ]
